### ISSUE TITLE
Exception: Use of const in strict mode

### ISSUE THREAD

**Issue by amolinaalvarez** [karimsa/gulp-jslint#32]
Using the latest version (1.0.1), I'm getting this exception:

const PluginError = require('gulp-util').PluginError,
^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)

**Comment by karimsa** [comment]
Constants are actually an ES6 feature, and that error tends to occur when you try to use them in a version of node that requires you to enable ES6 features manually.

Solutions: 

 1. You could upgrade your node version to 5.x and then ES6 features (mostly) will be natively available.
 2. Run node with the harmony flag (i.e. `node --harmony myscript.js` as opposed to `node myscript.js`)

More on this topic: stackoverflow.com/questions/22603078/syntaxerror-use-of-const-in-strict-mode
