### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by cowraliu** [karimsa/gulp-jslint#33]
![issue](https://cloud.githubusercontent.com/assets/13912782/15143856/6364f254-16de-11e6-8aee-8a6bc894ad98.png)
![source](https://cloud.githubusercontent.com/assets/13912782/15143930/dadebe1e-16de-11e6-9aa1-24979dc29a00.png)

**Comment by karimsa** [comment]
This should be fixed now (as of version 1.0.2).

**Comment by kiefferbp** [comment]
I'm having the same problem. It also doesn't appear that v1.0.2 is on npm.

**Comment by cowraliu** [comment]
Yes, but it doesn't matter. Because it can be got from Git by modifying your package.json as following:

"devDependencies": {
  "gulp": "^3.9.1",
  "gulp-jslint": "git+https://github.com/karimsa/gulp-jslint.git",
  "gulp-util": "^3.0.7"
} 

Good Luck!
