### ISSUE TITLE
Is there any support for ignoring unused parameters?

### ISSUE THREAD

**Issue by victorisildur** [karimsa/gulp-jslint#34]
> Jslint introduces a new reserved word: ignore. It is used in parameter lists and in catch clauses to indicate a parameter that will be ignored. Unused warnings will not be produced for ignore.

For many circumstances we have to introduce used param, like $.each() or addEventListener().

Any idea how to ignore such error?

**Comment by karimsa** [comment]
Try something like this:

```javascript
(function () {
    'use strict';

    var test = [];

    /*jslint ignore:start*/
    test.forEach(function (elm, index) {
        return elm;
    });
    /*jslint ignore:false*/
}());
```

It passed for me.
