### ISSUE TITLE
Issue with default reporter

### ISSUE THREAD

**Issue by zaun** [karimsa/gulp-jslint#35]
I had to update the report to use:

        results.errors
            .sort((a, b) => a && b && a.character && b.character ? a.character - b.character : 0)
            .sort((a, b) => a && b && a.column && b.column ? a.column - b.column : 0)
            .sort((a, b) => a && b && a.line && b.line ? a.line - b.line : 0)
            .forEach((res) => {if (res) subError('%s:%s: %s', res.line || '?', res.column || res.character || '?', res.message || res.reason)});

or things were failing with `undefined` errors.

**Comment by karimsa** [comment]
I'll update this as soon as possible. Thanks for reporting it

**Comment by JAAulde** [comment]
Thanks so much for reporting this and providing working code! It helped me out a lot this evening!

**Comment by karimsa** [comment]
Thanks for the code and reporting it! I have created a more long-term solution than the one I previously posted.
