### ISSUE TITLE
errors reported as "undefined : undefined" rather than including an error description

### ISSUE THREAD

**Issue by adrianwright** [karimsa/gulp-jslint#36]
gulp-jslint correctly flags errors, but doesn't include the description of the errors in the output.

Here's gulpfile.js:

```
var gulp = require('gulp'),
    jslint = require('gulp-jslint');

gulp.task('default', ['jslint-server']);

gulp.task('jslint-server', function () {
    return gulp.src([ // some example files
                    'scripts/*.js',
                    'web-server.js'
                ])
            .pipe(jslint({ node:true, bitwise:true }))
            .pipe(jslint.reporter( 'stylish' ));
});
```
And here's the output:

```
 ✓ config.js
 ✖ ConfigController.js
   ✖ 6:undefined: undefined
   ✖ 8:undefined: undefined
 ✓ FeaturesController.js
 ✓ web-server.js
```
It has correctly flagged two errors. However, I would expect to see a description of the errors where it says, "undefined : undefined".

Any advice on seeing the descriptions?

**Comment by karimsa** [comment]
Thanks for bringing this to my attention! It was actually similar to issue #35 (as Sven Schoenung mentioned on StackOverflow).

I have written a general solution for all reporters so it should work now. Please reopen if it still won't work.

The working version is: [1.0.3](https://github.com/karimsa/gulp-jslint/releases/tag/1.0.3).
